# Generated by Django 3.2.3 on 2021-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=200)),
                ('sent_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sent_at',),
            },
        ),
    ]
